name: App build
on: push

jobs:
  build_with_signing:
    runs-on: macos-26
    steps:
      - name: 🛠️ Checkout repository
        uses: actions/checkout@v4
        with:
            repository: saltpi/iPlay.Apple
            ref: 'dev/kernel'
            token: ${{ secrets.REPO_TOKEN }}
            submodules: recursive

      - name: 🔑 Import code sign
        continue-on-error: true
        uses: apple-actions/import-codesign-certs@v3
        with:
          p12-file-base64: ${{ secrets.BUILD_CERTIFICATE_BASE64 }}
          p12-password: ${{ secrets.BUILD_CERTIFICATE_PASSWORD }}
        
      - name: 📄 Download provisioning profiles
        uses: apple-actions/download-provisioning-profiles@v4
        with:
          bundle-id: top.ourfor.app.iPlayClient
          issuer-id: ${{ secrets.APPSTORE_ISSUER_ID }}
          api-key-id: ${{ secrets.APPSTORE_API_KEY_ID }}
          api-private-key: ${{ secrets.APPSTORE_API_PRIVATE_KEY }}

      - name: 🔐 Make signing keychain default & unlock
        run: |
          set -eux
          KEYCHAIN=~/Library/Keychains/signing_temp.keychain-db
          security list-keychains -s "$KEYCHAIN"
          security default-keychain -s "$KEYCHAIN"

      - name: 📄 Log info
        run: |
          security find-identity -p codesigning -v
          find ~/Library/MobileDevice/Provisioning\ Profiles/*.mobileprovision|xargs -I % security cms -D -i %
          ls -la ~/Library/MobileDevice/Provisioning\ Profiles
          

      - name: 🔢 Update Build Number
        id: update_build_number
        uses: ourfor/update-testflight-build-number@v3
        with:
          app-id: '6480576133'
          platform: 'IOS'
          issuer-id: ${{ secrets.APPSTORE_ISSUER_ID }}
          api-key-id: ${{ secrets.APPSTORE_API_KEY_ID }}
          api-private-key: ${{ secrets.APPSTORE_API_PRIVATE_KEY }}

      - name: 🧾 Print Build Number
        run: |
          echo "Build Number: ${{ steps.update_build_number.outputs.build-number }}"
          cat iPlay.xcodeproj/project.pbxproj | grep -A 1 'CURRENT_PROJECT_VERSION = '

      - name: 🚀 Build app
        shell: bash
        run: |
          next_build_number=$((${{ steps.update_build_number.outputs.build-number }} + 1))
          export BUILD_NUMBER=$next_build_number
          ./script/build.sh

      - name: ☁️ Upload to TestFlight
        uses: apple-actions/upload-testflight-build@v3
        with:
          app-path: .build/Artifacts/iPlay.ipa/iPlay.ipa
          issuer-id: ${{ secrets.APPSTORE_ISSUER_ID }}
          api-key-id: ${{ secrets.APPSTORE_API_KEY_ID }}
          api-private-key: ${{ secrets.APPSTORE_API_PRIVATE_KEY }}
